version: "3.1"

services:
  rentPG:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./data/postgresql/:/var/lib/postgresql/data/
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rent_dev
    networks:
      - rent
    ports:
      - 5432:5432

networks:
  rent:
    driver: bridge
